In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Harsh", "Rahul", "Priya"]
})

sales = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "product": ["Laptop", "Phone", "Mouse"],
    "amount": [55000, 25000, 1000]
})

In [3]:
merged_data = pd.merge(
    customers,
    sales,
    on="customer_id"
)

merged_data

   customer_id   name product  amount
0            1  Harsh  Laptop   55000
1            2  Rahul   Phone   25000
2            3  Priya   Mouse    1000

In [4]:
sales = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "product": ["Laptop", "Phone", "Mouse"],
    "amount": [55000, 25000, 1000]
})

sales

   customer_id product  amount
0            1  Laptop   55000
1            2   Phone   25000
2            3   Mouse    1000

In [5]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Harsh", "Rahul", "Priya", "Amit"]
})

customers

   customer_id   name
0            1  Harsh
1            2  Rahul
2            3  Priya
3            4   Amit

inner_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="inner"
)

inner_join

In [6]:
inner_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="inner"
)

inner_join

   customer_id   name product  amount
0            1  Harsh  Laptop   55000
1            2  Rahul   Phone   25000
2            3  Priya   Mouse    1000

In [7]:
left_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="left"
)

left_join

   customer_id   name product   amount
0            1  Harsh  Laptop  55000.0
1            2  Rahul   Phone  25000.0
2            3  Priya   Mouse   1000.0
3            4   Amit     NaN      NaN

In [8]:
import pandas as pd

In [ ]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Harsh", "Rahul", "Priya", "Amit"],
    "region": ["South", "West", "North", "South"]
})

customers

   customer_id   name region
0            1  Harsh  South
1            2  Rahul   West
2            3  Priya  North
3            4   Amit  South

In [10]:
sales = pd.DataFrame({
    "customer_id": [1, 2, 3, 5],
    "product": ["Laptop", "Phone", "Mouse", "Keyboard"],
    "amount": [55000, 25000, 1000, 3000]
})

sales

   customer_id   product  amount
0            1    Laptop   55000
1            2     Phone   25000
2            3     Mouse    1000
3            5  Keyboard    3000

In [ ]:
inner_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="inner"
)

inner_join

   customer_id   name region product  amount
0            1  Harsh  South  Laptop   55000
1            2  Rahul   West   Phone   25000
2            3  Priya  North   Mouse    1000

In [12]:
left_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="left"
)

left_join

   customer_id   name region product   amount
0            1  Harsh  South  Laptop  55000.0
1            2  Rahul   West   Phone  25000.0
2            3  Priya  North   Mouse   1000.0
3            4   Amit  South     NaN      NaN

In [ ]:
right_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="right"
)

right_join

   customer_id   name region   product  amount
0            1  Harsh  South    Laptop   55000
1            2  Rahul   West     Phone   25000
2            3  Priya  North     Mouse    1000
3            5    NaN    NaN  Keyboard    3000

In [14]:
outer_join = pd.merge(
    customers,
    sales,
    on="customer_id",
    how="outer"
)

outer_join

   customer_id   name region   product   amount
0            1  Harsh  South    Laptop  55000.0
1            2  Rahul   West     Phone  25000.0
2            3  Priya  North     Mouse   1000.0
3            4   Amit  South       NaN      NaN
4            5    NaN    NaN  Keyboard   3000.0

In [15]:
sales_data = pd.DataFrame({
    "region": ["South", "South", "West", "West", "North", "North"],
    "product": ["Laptop", "Phone", "Laptop", "Phone", "Laptop", "Phone"],
    "amount": [55000, 25000, 60000, 30000, 50000, 20000]
})

sales_data

  region product  amount
0  South  Laptop   55000
1  South   Phone   25000
2   West  Laptop   60000
3   West   Phone   30000
4  North  Laptop   50000
5  North   Phone   20000

In [16]:
pivot_table = pd.pivot_table(
    sales_data,
    values="amount",
    index="region",
    columns="product",
    aggfunc="sum"
)

pivot_table

product  Laptop  Phone
region
North     50000  20000
South     55000  25000
West      60000  30000

In [ ]:
wide_data = pd.DataFrame({
    "student": ["Harsh", "Rahul", "Priya"],
    "Math": [85, 78, 92],
    "Python": [90, 82, 95],
    "SQL": [88, 80, 91]
})

wide_data

  student  Math  Python  SQL
0   Harsh    85      90   88
1   Rahul    78      82   80
2   Priya    92      95   91

In [ ]:
employees = pd.DataFrame({
    "name": ["Harsh", "Rahul", "Priya", "Amit"],
    "department": ["IT", "Sales", "IT", "Sales"],
    "salary": [50000, 40000, 60000, 35000]
})

employees

    name department  salary
0  Harsh         IT   50000
1  Rahul      Sales   40000
2  Priya         IT   60000
3   Amit      Sales   35000

In [19]:
result = (
    employees
    .query("salary >= 40000")
    .sort_values("salary", ascending=False)
    .reset_index(drop=True)
)

result

    name department  salary
0  Priya         IT   60000
1  Harsh         IT   50000
2  Rahul      Sales   40000

In [20]:
final_result = (
    pd.merge(customers, sales, on="customer_id", how="left")
    .dropna(subset=["amount"])
    .sort_values("amount", ascending=False)
    .reset_index(drop=True)
)

final_result

   customer_id   name region product   amount
0            1  Harsh  South  Laptop  55000.0
1            2  Rahul   West   Phone  25000.0
2            3  Priya  North   Mouse   1000.0